name = "aubesee-admin"
account_id = "your-cloudflare-account-id"
workers_dev = true
compatibility_date = "2024-01-01"

[env.development]
vars = { PUBLIC_ADMINAPI_HOST="http://localhost:8085" }

[env.staging]
vars = { PUBLIC_ADMINAPI_HOST="https://aubesee-admin-stg.triple-a.rocks" }

[env.production]
vars = { PUBLIC_ADMINAPI_HOST="https://aubesee-admin.triple-a.rocks" }