name = "aube-admin-prev"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2024-01-01"


[env.preview.vars]
PUBLIC_ADMINAPI_HOST = "https://adminapi-stg.triple-a.rocks"
CF_ACCESS_CLIENT_ID = "4438507a04cd88506072a317f51607cd.access"
CF_ACCESS_CLIENT_SECRET = "ea2aa217caf121ba834b16a484cde92a98014f8abf7bcefdc7e7a199c0b814d2"

[env.production.vars]
PUBLIC_ADMINAPI_HOST = "https://adminapi-stg.triple-a.rocks"
CF_ACCESS_CLIENT_ID = "3edfc56d4fcf749bb26f4460b64942e0.access"
CF_ACCESS_CLIENT_SECRET = "f149af90c347dbd22e4fa71c63eb9ae7aad06dc7237dfc9b0b91caa459f6a2ac"