/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/admin/api/v1/rates': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * get latest rates
         * @description get latest rates for all supported currencies, not paginated
         */
        get: operations['get-admin-api-v1-latest-rates'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/admin/api/v1/accounts/{account-id}': {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description account id */
                'account-id': components['schemas']['AccountID'];
            };
            cookie?: never;
        };
        /**
         * get details on account
         * @description get details on specific account
         */
        get: operations['get-admin-api-v1-accounts-account-id'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/admin/api/v1/accounts/{account-id}/balances': {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description account id */
                'account-id': components['schemas']['AccountID'];
            };
            cookie?: never;
        };
        /**
         * get account balance
         * @description get balance for a specific account
         */
        get: operations['get-admin-api-v1-accounts-account-id-balance'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/admin/api/v1/accounts/{account-id}/transactions': {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description account id */
                'account-id': components['schemas']['AccountID'];
            };
            cookie?: never;
        };
        /**
         * list account transactions
         * @description list all transaction for a specific account
         */
        get: operations['get-admin-api-v1-accounts-account-id-transactions'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/admin/api/v1/accounts': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * get accounts
         * @description get a list of all accounts
         */
        get: operations['get-admin-api-v1-accounts'];
        put?: never;
        /**
         * create an account
         * @description create an account
         */
        post: operations['post-admin-api-v1-accounts'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/admin/api/v1/entities': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * get entities
         * @description get a list of all entities
         */
        get: operations['get-admin-api-v1-entities'];
        put?: never;
        /**
         * create an entity
         * @description create an entity
         */
        post: operations['post-admin-api-v1-entities'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/admin/api/v1/entities/{entity-id}': {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description entity id */
                'entity-id': components['schemas']['EntityID'];
            };
            cookie?: never;
        };
        /**
         * get entity
         * @description get an entity
         */
        get: operations['get-admin-api-v1-entity'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/admin/api/v1/entities/{entity-id}/accounts': {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description entity id */
                'entity-id': components['schemas']['EntityID'];
            };
            cookie?: never;
        };
        /**
         * get entity accounts
         * @description get all accounts related to the entity
         */
        get: operations['get-admin-api-v1-entity-accounts'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/admin/api/v1/compliance/legal-entities': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * get legal entities
         * @description get legal entities
         */
        get: operations['get-admin-api-v1-legal-entities'];
        put?: never;
        /**
         * create legal entity
         * @description create legal entity
         */
        post: operations['post-admin-api-v1-compliance-legal-entities'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/admin/api/v1/compliance/legal-entities/{legal-entity-id}': {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description legal entity id */
                'legal-entity-id': components['schemas']['LegalEntityID'];
            };
            cookie?: never;
        };
        /**
         * get legal entity
         * @description get legal entity
         */
        get: operations['get-admin-api-v1-compliance-legal-entities'];
        /**
         * update legal entity
         * @description update legal entity
         */
        put: operations['update-admin-api-v1-compliance-legal-entities'];
        post?: never;
        /**
         * delete legal entity
         * @description delete legal entity
         */
        delete: operations['delete-admin-api-v1-compliance-legal-entities'];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/admin/api/v1/compliance/legal-entities/{legal-entity-id}/related-parties': {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description legal entity id */
                'legal-entity-id': components['schemas']['LegalEntityID'];
            };
            cookie?: never;
        };
        /**
         * get related parties
         * @description get related parties
         */
        get: operations['get-admin-api-v1-compliance-legal-entities-related-parties'];
        put?: never;
        /**
         * create related party
         * @description create related party
         */
        post: operations['post-admin-api-v1-compliance-legal-entities-related-party'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/admin/api/v1/compliance/legal-entities/{legal-entity-id}/related-parties/{related-party-id}': {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description legal entity id */
                'legal-entity-id': components['schemas']['LegalEntityID'];
                /** @description related party id */
                'related-party-id': components['schemas']['LegalEntityRelatedPartyID'];
            };
            cookie?: never;
        };
        /**
         * get related party
         * @description get related party
         */
        get: operations['get-admin-api-v1-compliance-legal-entities-related-party'];
        /**
         * update related party
         * @description update related party
         */
        put: operations['update-admin-api-v1-compliance-legal-entities-related-party'];
        post?: never;
        /**
         * delete related party
         * @description delete related party
         */
        delete: operations['delete-admin-api-v1-compliance-legal-entities-related-party'];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/admin/api/v1/transactions': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * create a transaction
         * @description create a transaction
         */
        post: operations['post-admin-api-v1-transaction'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/admin/api/v1/const/industries': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * get industry list
         * @description get a list of all industries
         */
        get: operations['get-admin-api-v1-const-industries'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/admin/api/v1/const/occupations': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * get occupation list
         * @description get a list of all occupations
         */
        get: operations['get-admin-api-v1-const-occupations'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CreateEntityIndividual */
        CreateEntityIndividual: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            entity_type: 'individual';
            /**
             * Format: email
             * @example random@example.com
             */
            email: string;
            gender: components['schemas']['Gender'];
            /** @example John */
            first_name: string;
            /** @example Doe */
            last_name: string;
            /** @example 53 Sungei Tengah Rd */
            street: string;
            /** @example Singapore */
            city: string;
            /** @example 698998 */
            postal_code: string;
            country: components['schemas']['CountryCode2'];
            nationality: components['schemas']['CountryCode2'];
            birth_country: components['schemas']['CountryCode2'];
            birth_date: components['schemas']['Date'];
            /** @example Paris */
            birth_place: string;
        };
        /** CreateEntityCorporate */
        CreateEntityCorporate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            entity_type: 'corporate';
            /**
             * Format: email
             * @example random@example.com
             */
            email: string;
            /** @example Blk 447 Clementi Ave 3 #01-201 S() */
            street: string;
            /** @example singapore */
            city: string;
            /** @example 120447 */
            postal_code: string;
            country: components['schemas']['CountryCode2'];
            /** @example Wisoky - Berge */
            company_name: string;
            registration_country: components['schemas']['CountryCode2'];
            incorporation_date: components['schemas']['Date'];
        };
        CreateEntity:
            | components['schemas']['CreateEntityIndividual']
            | components['schemas']['CreateEntityCorporate'];
        /** CreateLegalEntityCorporate */
        CreateLegalEntityCorporate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            entity_type: 'corporate';
            kyb_status: components['schemas']['KybStatus'];
            onboarding_mode: components['schemas']['OnboardingMode'];
            /** @example Example Corp */
            company_name: string;
            /** @example [
             *       "Example Corp"
             *     ] */
            alias_names: string[];
            /** @example [
             *       "Example Corp"
             *     ] */
            trade_names: string[];
            /** @example [
             *       "Example Corp"
             *     ] */
            former_registered_names: string[];
            incorporation_date: components['schemas']['Date'];
            /** @example 12345678 */
            incorporation_number: string;
            incorporation_country: components['schemas']['CountryCode2'];
            operation_countries: components['schemas']['CountryCode2'][];
            /** @example [
             *       "https://example.com",
             *       "https://example.org"
             *     ] */
            websites: string[];
            /** @example 1 */
            industry_id: number;
            /** @example [
             *       "1234",
             *       "5678"
             *     ] */
            mcc_codes: string[];
            /** @example [
             *       "software development",
             *       "consulting"
             *     ] */
            business_activities: string[];
            /** @example [
             *       "investors",
             *       "revenue"
             *     ] */
            sources_of_fund: string[];
            addresses: components['schemas']['CreateEntityAddress'][];
        };
        /** CreateLegalEntityIndividual */
        CreateLegalEntityIndividual: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            entity_type: 'individual';
            kyb_status: components['schemas']['KybStatus'];
            onboarding_mode: components['schemas']['OnboardingMode'];
            /** @example John */
            first_name: string;
            /** @example Doe */
            last_name: string;
            /** @example [
             *       "John D"
             *     ] */
            alias_names: string[];
            gender: components['schemas']['Gender'];
            nationalities: components['schemas']['CountryCode2'][];
            birth_country: components['schemas']['CountryCode2'];
            birth_date: components['schemas']['Date'];
            residence_country: components['schemas']['CountryCode2'];
            /** @example International Passport */
            identity_document_type: string;
            /** @example 123456 */
            identity_document_number: string;
            identity_document_issue_date: components['schemas']['Date'];
            identity_document_expiry_date: components['schemas']['Date'];
            /** @example 1 */
            occupation_id: number;
            /** @example [
             *       "investors",
             *       "revenue"
             *     ] */
            sources_of_fund: string[];
            addresses: components['schemas']['CreateEntityAddress'][];
        };
        CreateLegalEntity:
            | components['schemas']['CreateLegalEntityIndividual']
            | components['schemas']['CreateLegalEntityCorporate'];
        /** UpdateLegalEntityCorporate */
        UpdateLegalEntityCorporate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            entity_type: 'corporate';
            kyb_status: components['schemas']['KybStatus'];
            onboarding_mode: components['schemas']['OnboardingMode'];
            /** @example Example Corp */
            company_name: string;
            /** @example [
             *       "Example Corp"
             *     ] */
            alias_names: string[];
            /** @example [
             *       "Example Corp"
             *     ] */
            trade_names: string[];
            /** @example [
             *       "Example Corp"
             *     ] */
            former_registered_names: string[];
            incorporation_date: components['schemas']['Date'];
            /** @example 12345678 */
            incorporation_number: string;
            incorporation_country: components['schemas']['CountryCode2'];
            operation_countries: components['schemas']['CountryCode2'][];
            /** @example [
             *       "https://example.com",
             *       "https://example.org"
             *     ] */
            websites: string[];
            /** @example Technology */
            industry_id: number;
            /** @example [
             *       "1234",
             *       "5678"
             *     ] */
            mcc_codes: string[];
            /** @example [
             *       "Software Development",
             *       "Consulting"
             *     ] */
            business_activities: string[];
            /** @example [
             *       "Investors",
             *       "Revenue"
             *     ] */
            sources_of_fund: string[];
            addresses: components['schemas']['UpdateEntityAddress'][];
        };
        /** UpdateLegalEntityIndividual */
        UpdateLegalEntityIndividual: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            entity_type: 'individual';
            kyb_status: components['schemas']['KybStatus'];
            onboarding_mode: components['schemas']['OnboardingMode'];
            /** @example John */
            first_name: string;
            /** @example Doe */
            last_name: string;
            /** @example [
             *       "John D"
             *     ] */
            alias_names: string[];
            gender: components['schemas']['Gender'];
            nationalities: components['schemas']['CountryCode2'][];
            birth_country: components['schemas']['CountryCode2'];
            birth_date: components['schemas']['Date'];
            residence_country: components['schemas']['CountryCode2'];
            /** @example International Passport */
            identity_document_type: string;
            /** @example 123456 */
            identity_document_number: string;
            identity_document_issue_date: components['schemas']['Date'];
            identity_document_expiry_date: components['schemas']['Date'];
            /** @example [
             *       "Investors",
             *       "Revenue"
             *     ] */
            sources_of_fund: string[];
            addresses: components['schemas']['UpdateEntityAddress'][];
        };
        UpdateLegalEntity:
            | components['schemas']['UpdateLegalEntityIndividual']
            | components['schemas']['UpdateLegalEntityCorporate'];
        /** CreateLegalEntityRelatedPartyCorporate */
        CreateLegalEntityRelatedPartyCorporate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            entity_type: 'corporate';
            /** @example Example Corp */
            company_name: string;
            /** @example [
             *       "Example Corp"
             *     ] */
            alias_names: string[];
            /** @example [
             *       "Example Corp"
             *     ] */
            trade_names: string[];
            /** @example [
             *       "Example Corp"
             *     ] */
            former_registered_names: string[];
            incorporation_date: components['schemas']['Date'];
            /** @example 12345678 */
            incorporation_number: string;
            incorporation_country: components['schemas']['CountryCode2'];
            operation_countries: components['schemas']['CountryCode2'][];
            /** @example [
             *       "https://example.com",
             *       "https://example.org"
             *     ] */
            websites: string[];
            /** @example Technology */
            industry: string;
            /** @example [
             *       "1234",
             *       "5678"
             *     ] */
            mcc_codes: string[];
            /** @example [
             *       "Software Development",
             *       "Consulting"
             *     ] */
            business_activities: string[];
            addresses: components['schemas']['CreateEntityAddress'][];
            roles: components['schemas']['RelatedPartyRoles'][];
            ownership_structure: number;
        };
        /** CreateLegalEntityRelatedPartyIndividual */
        CreateLegalEntityRelatedPartyIndividual: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            entity_type: 'individual';
            /** @example John */
            first_name: string;
            /** @example Doe */
            last_name: string;
            /** @example [
             *       "John D"
             *     ] */
            alias_names: string[];
            gender: components['schemas']['Gender'];
            nationalities: components['schemas']['CountryCode2'][];
            birth_country: components['schemas']['CountryCode2'];
            birth_date: components['schemas']['Date'];
            residence_country: components['schemas']['CountryCode2'];
            /** @example International Passport */
            identity_document_type: string;
            /** @example 123456 */
            identity_document_number: string;
            identity_document_issue_date: components['schemas']['Date'];
            identity_document_expiry_date: components['schemas']['Date'];
            addresses: components['schemas']['CreateEntityAddress'][];
            roles: components['schemas']['RelatedPartyRoles'][];
        };
        CreateLegalEntityRelatedParty:
            | components['schemas']['CreateLegalEntityRelatedPartyIndividual']
            | components['schemas']['CreateLegalEntityRelatedPartyCorporate'];
        /** UpdateLegalEntityRelatedPartyCorporate */
        UpdateLegalEntityRelatedPartyCorporate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            entity_type: 'corporate';
            /** @example Example Corp */
            company_name: string;
            /** @example [
             *       "Example Corp"
             *     ] */
            alias_names: string[];
            /** @example [
             *       "Example Corp"
             *     ] */
            trade_names: string[];
            /** @example [
             *       "Example Corp"
             *     ] */
            former_registered_names: string[];
            incorporation_date: components['schemas']['Date'];
            /** @example 12345678 */
            incorporation_number: string;
            incorporation_country: components['schemas']['CountryCode2'];
            operation_countries: components['schemas']['CountryCode2'][];
            /** @example [
             *       "https://example.com",
             *       "https://example.org"
             *     ] */
            websites: string[];
            /** @example Technology */
            industry: string;
            /** @example [
             *       "1234",
             *       "5678"
             *     ] */
            mcc_codes: string[];
            /** @example [
             *       "Software Development",
             *       "Consulting"
             *     ] */
            business_activities: string[];
            addresses: components['schemas']['UpdateEntityAddress'][];
            roles: components['schemas']['RelatedPartyRoles'][];
            ownership_structure: number;
        };
        /** UpdateLegalEntityRelatedPartyIndividual */
        UpdateLegalEntityRelatedPartyIndividual: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            entity_type: 'individual';
            /** @example John */
            first_name: string;
            /** @example Doe */
            last_name: string;
            /** @example [
             *       "John D"
             *     ] */
            alias_names: string[];
            gender: components['schemas']['Gender'];
            nationalities: components['schemas']['CountryCode2'][];
            birth_country: components['schemas']['CountryCode2'];
            birth_date: components['schemas']['Date'];
            residence_country: components['schemas']['CountryCode2'];
            /** @example International Passport */
            identity_document_type: string;
            /** @example 123456 */
            identity_document_number: string;
            identity_document_issue_date: components['schemas']['Date'];
            identity_document_expiry_date: components['schemas']['Date'];
            addresses: components['schemas']['UpdateEntityAddress'][];
            roles: components['schemas']['RelatedPartyRoles'][];
        };
        UpdateLegalEntityRelatedParty:
            | components['schemas']['UpdateLegalEntityRelatedPartyIndividual']
            | components['schemas']['UpdateLegalEntityRelatedPartyCorporate'];
        /** EntityAddress */
        CreateEntityAddress: {
            /** @example 1st main street */
            address_line_one?: string;
            /** @example Tower One #01-50 */
            address_line_two?: string;
            /** @example SG */
            city?: string;
            /** @example Singapore */
            state_region?: string;
            /** @example 609431 */
            postal_code?: string;
            country: components['schemas']['CountryCode2'];
        };
        /** EntityAddress */
        UpdateEntityAddress: {
            /** @example addr-ykrit3642ha2gzdthfagghbnme */
            id?: string;
            /** @example 1st main street */
            address_line_one?: string;
            /** @example Tower One #01-50 */
            address_line_two?: string;
            /** @example SG */
            city?: string;
            /** @example Singapore */
            state_region?: string;
            /** @example 609431 */
            postal_code?: string;
            country: components['schemas']['CountryCode2'];
        };
        /** CreateEntityIndividual */
        CreateTransaction: {
            from_account_id: components['schemas']['AccountID'];
            to_account_id: components['schemas']['AccountID'];
            amount: components['schemas']['Decimal'];
        };
        /**
         * UUID
         * Format: uuid
         * @description UUID can be either v7 or v2
         * @example 123e4567-e89b-12d3-a456-426614174000
         */
        UUID: string;
        /**
         * CurrencyCode
         * @description currency codes
         * @example EUR
         * @enum {string}
         */
        CurrencyCode:
            | 'AED'
            | 'ALL'
            | 'AMD'
            | 'ANG'
            | 'AOA'
            | 'ARS'
            | 'AUD'
            | 'AWG'
            | 'AZN'
            | 'BAM'
            | 'BBD'
            | 'BDT'
            | 'BGN'
            | 'BHD'
            | 'BMD'
            | 'BNB'
            | 'BND'
            | 'BOB'
            | 'BRL'
            | 'BSD'
            | 'BTC'
            | 'BWP'
            | 'BYN'
            | 'BZD'
            | 'CAD'
            | 'CHF'
            | 'CLP'
            | 'CNH'
            | 'CNY'
            | 'COP'
            | 'CRC'
            | 'CUP'
            | 'CVE'
            | 'CZK'
            | 'DJF'
            | 'DKK'
            | 'DOP'
            | 'DZD'
            | 'EGP'
            | 'ETB'
            | 'ETH'
            | 'EUR'
            | 'FJD'
            | 'FKP'
            | 'GBP'
            | 'GEL'
            | 'GHS'
            | 'GIP'
            | 'GMD'
            | 'GNF'
            | 'GTQ'
            | 'GYD'
            | 'HKD'
            | 'HNL'
            | 'HTG'
            | 'HUF'
            | 'IDR'
            | 'ILS'
            | 'INR'
            | 'IQD'
            | 'ISK'
            | 'JMD'
            | 'JOD'
            | 'JPY'
            | 'KES'
            | 'KGS'
            | 'KHR'
            | 'KMF'
            | 'KRW'
            | 'KWD'
            | 'KYD'
            | 'KZT'
            | 'LAK'
            | 'LBP'
            | 'LKR'
            | 'LYD'
            | 'MAD'
            | 'MATIC'
            | 'MDL'
            | 'MKD'
            | 'MMK'
            | 'MNT'
            | 'MOP'
            | 'MRU'
            | 'MUR'
            | 'MVR'
            | 'MWK'
            | 'MXN'
            | 'MYR'
            | 'MZN'
            | 'NAD'
            | 'NGN'
            | 'NIO'
            | 'NOK'
            | 'NPR'
            | 'NZD'
            | 'OMR'
            | 'PAB'
            | 'PEN'
            | 'PGK'
            | 'PHP'
            | 'PKR'
            | 'PLN'
            | 'PYG'
            | 'QAR'
            | 'RON'
            | 'RSD'
            | 'RUB'
            | 'RWF'
            | 'SAR'
            | 'SBD'
            | 'SCR'
            | 'SEK'
            | 'SGD'
            | 'SHP'
            | 'SLE'
            | 'SOL'
            | 'SOS'
            | 'SRD'
            | 'STN'
            | 'SVC'
            | 'SZL'
            | 'THB'
            | 'TND'
            | 'TOP'
            | 'TRX'
            | 'TRY'
            | 'TTD'
            | 'TWD'
            | 'TZS'
            | 'UAH'
            | 'UGX'
            | 'USD'
            | 'USDC'
            | 'USDT'
            | 'UYU'
            | 'UZS'
            | 'VEF'
            | 'VND'
            | 'VUV'
            | 'WST'
            | 'XAF'
            | 'XCD'
            | 'XLM'
            | 'XOF'
            | 'XPF'
            | 'XSGD'
            | 'YER'
            | 'ZAR'
            | 'ZMW';
        /**
         * Decimal
         * Format: decimal
         * @description decimals 0.000001
         * @example 0.1
         */
        Decimal: string;
        /**
         * Datetime
         * Format: date-time
         * @example [
         *       "2024-06-08T17:28:39.859284+08:00"
         *     ]
         */
        Datetime: string;
        /**
         * MedianFxRateV1
         * @description rates with complete descriptions
         * @example [
         *       {
         *         "id": "018ffbf3-8fe6-7b4d-b7a3-20a87a989470",
         *         "version": 1,
         *         "providers_contrib": {
         *           "bitfinex": 4,
         *           "coinbase": 40,
         *           "kraken": 1
         *         },
         *         "providers_medians": {
         *           "bitfinex": "0.6666",
         *           "coinbase": "0.7777",
         *           "kraken": "0.88888"
         *         },
         *         "rates_count": 45,
         *         "outliers_perc": 0,
         *         "created_at": "2024-06-09T07:43:13.812496278Z",
         *         "base": "SOL",
         *         "quote": "USD",
         *         "rate_base_quote": "159.46",
         *         "rate_base_usd": "159.46",
         *         "rate_usd_quote": "0.0062711651824909"
         *       }
         *     ]
         */
        MedianFxRateV1: {
            id: components['schemas']['UUID'];
            /**
             * Format: int32
             * @example 1
             */
            version: number;
            base?: components['schemas']['CurrencyCode'];
            quote?: components['schemas']['CurrencyCode'];
            rate_base_quote?: components['schemas']['Decimal'];
            rate_base_usd?: components['schemas']['Decimal'];
            rate_usd_quote?: components['schemas']['Decimal'];
            /** @example {
             *       "provider1": 5,
             *       "provider2": 3
             *     } */
            providers_contrib: {
                [key: string]: number;
            };
            /** @example {
             *       "provider1": "5",
             *       "provider2": "3"
             *     } */
            providers_medians: {
                [key: string]: components['schemas']['Decimal'];
            };
            /**
             * Format: int64
             * @example 100
             */
            rates_count: number;
            /**
             * Format: int32
             * @example 5
             */
            outliers_perc: number;
            created_at: components['schemas']['Datetime'];
        };
        /**
         * Rates
         * @description rates map
         * @example [
         *       {
         *         "SOL": {
         *           "id": "018ffbf3-8fe6-7b4d-b7a3-20a87a989470",
         *           "version": 1,
         *           "providers_contrib": {
         *             "bitfinex": 4,
         *             "coinbase": 40,
         *             "kraken": 1
         *           },
         *           "providers_medians": {
         *             "bitfinex": "0.0062711651824909",
         *             "coinbase": "0.006473716518249",
         *             "kraken": "0.0061776878558"
         *           },
         *           "rates_count": 45,
         *           "outliers_perc": 0,
         *           "created_at": "2024-06-09T07:43:13.812496278Z",
         *           "base": "SOL",
         *           "quote": "USD",
         *           "rate_base_quote": "159.46",
         *           "rate_base_usd": "159.46",
         *           "rate_usd_quote": "0.0062711651824909"
         *         },
         *         "ETH": {
         *           "id": "018ffbf3-8fe6-7b4d-b7a3-20a87a989470",
         *           "version": 1,
         *           "providers_contrib": {
         *             "bitfinex": 4,
         *             "coinbase": 40,
         *             "kraken": 1
         *           },
         *           "providers_medians": {
         *             "bitfinex": "0.0062711651824909",
         *             "coinbase": "0.006473716518249",
         *             "kraken": "0.0061776878558"
         *           },
         *           "rates_count": 45,
         *           "outliers_perc": 0,
         *           "created_at": "2024-06-09T07:43:13.812496278Z",
         *           "base": "ETH",
         *           "quote": "USD",
         *           "rate_base_quote": "159.46",
         *           "rate_base_usd": "159.46",
         *           "rate_usd_quote": "0.0062711651824909"
         *         }
         *       }
         *     ]
         */
        Rates: {
            [key: string]: components['schemas']['MedianFxRateV1'];
        };
        /**
         * ProblemDetail
         * @description RFC9457
         */
        ProblemDetail: {
            /** @example https://example.com/probs/out-of-credit */
            type: string;
            /** @example You do not have enough credit. */
            title: string;
            /** @example Your current balance is 30, but that costs 50. */
            detail: string;
            /** @example /account/12345/msgs/abc */
            instance: string;
        };
        /**
         * account id
         * @description account id on the ledger
         * @example lacc-01j6pe0975kztejnkzrd0q1hax
         */
        AccountID: string;
        /**
         * Label
         * @description label
         * @example euro iban
         */
        Label: string;
        /**
         * NetworkCurrencyID
         * @example EUR
         * @enum {string}
         */
        NetworkCurrencyID:
            | 'AED'
            | 'ALL'
            | 'AMD'
            | 'ANG'
            | 'AOA'
            | 'ARS'
            | 'AUD'
            | 'AWG'
            | 'AZN'
            | 'BAM'
            | 'BBD'
            | 'BDT'
            | 'BGN'
            | 'BHD'
            | 'BMD'
            | 'BND'
            | 'BOB'
            | 'BRL'
            | 'BSD'
            | 'BWP'
            | 'BYN'
            | 'BZD'
            | 'CAD'
            | 'CHF'
            | 'CLP'
            | 'CNH'
            | 'CNY'
            | 'COP'
            | 'CRC'
            | 'CUP'
            | 'CVE'
            | 'CZK'
            | 'DJF'
            | 'DKK'
            | 'DOP'
            | 'DZD'
            | 'EGP'
            | 'ETB'
            | 'EUR'
            | 'FJD'
            | 'FKP'
            | 'GBP'
            | 'GEL'
            | 'GHS'
            | 'GIP'
            | 'GMD'
            | 'GNF'
            | 'GTQ'
            | 'GYD'
            | 'HKD'
            | 'HNL'
            | 'HTG'
            | 'HUF'
            | 'IDR'
            | 'ILS'
            | 'INR'
            | 'IQD'
            | 'ISK'
            | 'JMD'
            | 'JOD'
            | 'JPY'
            | 'KES'
            | 'KGS'
            | 'KHR'
            | 'KMF'
            | 'KRW'
            | 'KWD'
            | 'KYD'
            | 'KZT'
            | 'LAK'
            | 'LBP'
            | 'LKR'
            | 'LYD'
            | 'MAD'
            | 'MDL'
            | 'MKD'
            | 'MMK'
            | 'MNT'
            | 'MOP'
            | 'MRU'
            | 'MUR'
            | 'MVR'
            | 'MWK'
            | 'MXN'
            | 'MYR'
            | 'MZN'
            | 'NAD'
            | 'NGN'
            | 'NIO'
            | 'NOK'
            | 'NPR'
            | 'NZD'
            | 'OMR'
            | 'PAB'
            | 'PEN'
            | 'PGK'
            | 'PHP'
            | 'PKR'
            | 'PLN'
            | 'PYG'
            | 'QAR'
            | 'RON'
            | 'RSD'
            | 'RUB'
            | 'RWF'
            | 'SAR'
            | 'SBD'
            | 'SCR'
            | 'SEK'
            | 'SGD'
            | 'SHP'
            | 'SLE'
            | 'SOS'
            | 'SRD'
            | 'STN'
            | 'SVC'
            | 'SZL'
            | 'THB'
            | 'TND'
            | 'TOP'
            | 'TRY'
            | 'TTD'
            | 'TWD'
            | 'TZS'
            | 'UAH'
            | 'UGX'
            | 'USD'
            | 'UYU'
            | 'UZS'
            | 'VEF'
            | 'VND'
            | 'VUV'
            | 'WST'
            | 'XAF'
            | 'XCD'
            | 'XOF'
            | 'XPF'
            | 'YER'
            | 'ZAR'
            | 'ZMW'
            | 'BINANCE_BNB'
            | 'BITCOIN_BTC'
            | 'ETHEREUM_ETH'
            | 'ETHEREUM_USDC'
            | 'ETHEREUM_USDT'
            | 'POLYGON_MATIC'
            | 'POLYGON_XSGD'
            | 'POLYGON_USDC'
            | 'POLYGON_USDT'
            | 'SOLANA_SOL'
            | 'SOLANA_USDC'
            | 'SOLANA_USDT'
            | 'STELLAR_XLM'
            | 'STELLAR_USDC'
            | 'TRON_TRX'
            | 'TRON_USDC'
            | 'TRON_USDT'
            | 'VIRTUAL_USDT'
            | 'VIRTUAL_USDC'
            | 'VIRTUAL_XSGD';
        /**
         * AccountCategory
         * @example [
         *       "bank_account"
         *     ]
         * @enum {string}
         */
        AccountCategory: 'bank_account' | 'crypto_account' | 'virtual_account';
        /**
         * AccountLocality
         * @example [
         *       "internal"
         *     ]
         * @enum {string}
         */
        AccountLocality: 'internal' | 'external';
        /**
         * EntityID
         * @description entity id
         * @example ent-ykrit3642ha2gzdthfagghbnme
         */
        EntityID: string;
        /** bank account */
        BankAccount: {
            id?: components['schemas']['AccountID'];
            label?: components['schemas']['Label'];
            network_currency_id?: components['schemas']['NetworkCurrencyID'];
            /** @example FR7600008000020100000000000 */
            iban?: string;
            /** @example PAOTFRP1XXX */
            bic?: string;
            account_category?: components['schemas']['AccountCategory'];
            account_locality?: components['schemas']['AccountLocality'];
            owner_entity_id?: components['schemas']['EntityID'];
            /** @example mainsys */
            provider?: string;
            created_at?: components['schemas']['Datetime'];
        };
        /** VirtualAccount */
        VirtualAccount: {
            id?: components['schemas']['AccountID'];
            label?: components['schemas']['Label'];
            network_currency_id?: components['schemas']['NetworkCurrencyID'];
            balance?: components['schemas']['Decimal'];
            account_category?: components['schemas']['AccountCategory'];
            account_locality?: components['schemas']['AccountLocality'];
            created_at?: components['schemas']['Datetime'];
        };
        /** CryptoAddress */
        CryptoAddress: string;
        /** crypto account */
        CryptoAccount: {
            id?: components['schemas']['AccountID'];
            label?: components['schemas']['Label'];
            network_currency_id?: components['schemas']['NetworkCurrencyID'];
            balance?: components['schemas']['Decimal'];
            account_category?: components['schemas']['AccountCategory'];
            account_locality?: components['schemas']['AccountLocality'];
            created_at?: components['schemas']['Datetime'];
            address?: components['schemas']['CryptoAddress'];
        };
        Balance: {
            network_currency_id?: components['schemas']['NetworkCurrencyID'];
            posted_balance?: components['schemas']['Decimal'];
            pending_balance?: components['schemas']['Decimal'];
        };
        /**
         * BusinessID
         * @description business operation id
         * @example ope-ykrit3642ha2gzdthfagghbnme
         */
        BusinessID: string;
        /**
         * Transaction
         * @description ledger transaction
         */
        LedgerTransaction: {
            business_id: components['schemas']['BusinessID'];
            from_account_id: components['schemas']['AccountID'];
            to_account_id: components['schemas']['AccountID'];
            amount: components['schemas']['Decimal'];
            amount_usd: components['schemas']['Decimal'];
            /** @default false */
            pending: boolean;
            created_at: components['schemas']['Datetime'];
        };
        /**
         * UUIDv7
         * Format: uuid
         * @example 018e15ba-ff46-7023-540b-bffb6d3518e4
         */
        UUIDv7: string;
        /**
         * NetworkCurrencyID
         * @example FIAT_TEST_USD
         * @enum {string}
         */
        TestNetworkCurrencyID:
            | 'AMOY_MATIC'
            | 'AMOY_XSGD'
            | 'AMOY_USDC'
            | 'AMOY_USDT'
            | 'ANVIL_ETH'
            | 'BINANCE_TESTNET_BNB'
            | 'BITCOIN_TESTNET_BTC'
            | 'FIAT_TEST_AED'
            | 'FIAT_TEST_ALL'
            | 'FIAT_TEST_AMD'
            | 'FIAT_TEST_ANG'
            | 'FIAT_TEST_AOA'
            | 'FIAT_TEST_ARS'
            | 'FIAT_TEST_AUD'
            | 'FIAT_TEST_AWG'
            | 'FIAT_TEST_AZN'
            | 'FIAT_TEST_BAM'
            | 'FIAT_TEST_BBD'
            | 'FIAT_TEST_BDT'
            | 'FIAT_TEST_BGN'
            | 'FIAT_TEST_BHD'
            | 'FIAT_TEST_BMD'
            | 'FIAT_TEST_BND'
            | 'FIAT_TEST_BOB'
            | 'FIAT_TEST_BRL'
            | 'FIAT_TEST_BSD'
            | 'FIAT_TEST_BWP'
            | 'FIAT_TEST_BYN'
            | 'FIAT_TEST_BZD'
            | 'FIAT_TEST_CAD'
            | 'FIAT_TEST_CHF'
            | 'FIAT_TEST_CLP'
            | 'FIAT_TEST_CNH'
            | 'FIAT_TEST_CNY'
            | 'FIAT_TEST_COP'
            | 'FIAT_TEST_CRC'
            | 'FIAT_TEST_CUP'
            | 'FIAT_TEST_CVE'
            | 'FIAT_TEST_CZK'
            | 'FIAT_TEST_DJF'
            | 'FIAT_TEST_DKK'
            | 'FIAT_TEST_DOP'
            | 'FIAT_TEST_DZD'
            | 'FIAT_TEST_EGP'
            | 'FIAT_TEST_ETB'
            | 'FIAT_TEST_EUR'
            | 'FIAT_TEST_FJD'
            | 'FIAT_TEST_FKP'
            | 'FIAT_TEST_GBP'
            | 'FIAT_TEST_GEL'
            | 'FIAT_TEST_GHS'
            | 'FIAT_TEST_GIP'
            | 'FIAT_TEST_GMD'
            | 'FIAT_TEST_GNF'
            | 'FIAT_TEST_GTQ'
            | 'FIAT_TEST_GYD'
            | 'FIAT_TEST_HKD'
            | 'FIAT_TEST_HNL'
            | 'FIAT_TEST_HTG'
            | 'FIAT_TEST_HUF'
            | 'FIAT_TEST_IDR'
            | 'FIAT_TEST_ILS'
            | 'FIAT_TEST_INR'
            | 'FIAT_TEST_IQD'
            | 'FIAT_TEST_ISK'
            | 'FIAT_TEST_JMD'
            | 'FIAT_TEST_JOD'
            | 'FIAT_TEST_JPY'
            | 'FIAT_TEST_KES'
            | 'FIAT_TEST_KGS'
            | 'FIAT_TEST_KHR'
            | 'FIAT_TEST_KMF'
            | 'FIAT_TEST_KRW'
            | 'FIAT_TEST_KWD'
            | 'FIAT_TEST_KYD'
            | 'FIAT_TEST_KZT'
            | 'FIAT_TEST_LAK'
            | 'FIAT_TEST_LBP'
            | 'FIAT_TEST_LKR'
            | 'FIAT_TEST_LYD'
            | 'FIAT_TEST_MAD'
            | 'FIAT_TEST_MDL'
            | 'FIAT_TEST_MKD'
            | 'FIAT_TEST_MMK'
            | 'FIAT_TEST_MNT'
            | 'FIAT_TEST_MOP'
            | 'FIAT_TEST_MRU'
            | 'FIAT_TEST_MUR'
            | 'FIAT_TEST_MVR'
            | 'FIAT_TEST_MWK'
            | 'FIAT_TEST_MXN'
            | 'FIAT_TEST_MYR'
            | 'FIAT_TEST_MZN'
            | 'FIAT_TEST_NAD'
            | 'FIAT_TEST_NGN'
            | 'FIAT_TEST_NIO'
            | 'FIAT_TEST_NOK'
            | 'FIAT_TEST_NPR'
            | 'FIAT_TEST_NZD'
            | 'FIAT_TEST_OMR'
            | 'FIAT_TEST_PAB'
            | 'FIAT_TEST_PEN'
            | 'FIAT_TEST_PGK'
            | 'FIAT_TEST_PHP'
            | 'FIAT_TEST_PKR'
            | 'FIAT_TEST_PLN'
            | 'FIAT_TEST_PYG'
            | 'FIAT_TEST_QAR'
            | 'FIAT_TEST_RON'
            | 'FIAT_TEST_RSD'
            | 'FIAT_TEST_RUB'
            | 'FIAT_TEST_RWF'
            | 'FIAT_TEST_SAR'
            | 'FIAT_TEST_SBD'
            | 'FIAT_TEST_SCR'
            | 'FIAT_TEST_SEK'
            | 'FIAT_TEST_SGD'
            | 'FIAT_TEST_SHP'
            | 'FIAT_TEST_SLE'
            | 'FIAT_TEST_SOS'
            | 'FIAT_TEST_SRD'
            | 'FIAT_TEST_STN'
            | 'FIAT_TEST_SVC'
            | 'FIAT_TEST_SZL'
            | 'FIAT_TEST_THB'
            | 'FIAT_TEST_TND'
            | 'FIAT_TEST_TOP'
            | 'FIAT_TEST_TRY'
            | 'FIAT_TEST_TTD'
            | 'FIAT_TEST_TWD'
            | 'FIAT_TEST_TZS'
            | 'FIAT_TEST_UAH'
            | 'FIAT_TEST_UGX'
            | 'FIAT_TEST_USD'
            | 'FIAT_TEST_UYU'
            | 'FIAT_TEST_UZS'
            | 'FIAT_TEST_VEF'
            | 'FIAT_TEST_VND'
            | 'FIAT_TEST_VUV'
            | 'FIAT_TEST_WST'
            | 'FIAT_TEST_XAF'
            | 'FIAT_TEST_XCD'
            | 'FIAT_TEST_XOF'
            | 'FIAT_TEST_XPF'
            | 'FIAT_TEST_YER'
            | 'FIAT_TEST_ZAR'
            | 'FIAT_TEST_ZMW'
            | 'MUMBAI_MATIC'
            | 'MUMBAI_XSGD'
            | 'MUMBAI_USDC'
            | 'MUMBAI_USDT'
            | 'NILE_TRX'
            | 'NILE_USDC'
            | 'NILE_USDT'
            | 'SEPOLIA_ETH'
            | 'SEPOLIA_USDC'
            | 'SEPOLIA_USDT'
            | 'SHASTA_TRX'
            | 'SHASTA_USDC'
            | 'SHASTA_USDT'
            | 'SOLANA_TESTNET_SOL'
            | 'SOLANA_TESTNET_USDC'
            | 'SOLANA_TESTNET_USDT'
            | 'STELLAR_TESTNET_XLM'
            | 'STELLAR_TESTNET_USDC'
            | 'VIRTUAL_TEST_USDT'
            | 'VIRTUAL_TEST_USDC'
            | 'VIRTUAL_TEST_XSGD';
        /** NetworkCurrencyID */
        AnyNetworkCurrencyID: string &
            (
                | components['schemas']['NetworkCurrencyID']
                | components['schemas']['TestNetworkCurrencyID']
            );
        /**
         * Gender
         * @example male
         * @enum {string}
         */
        Gender: 'male' | 'female' | 'other';
        /**
         * CountryCode2
         * @example FR
         * @enum {string}
         */
        CountryCode2:
            | 'AW'
            | 'AF'
            | 'AO'
            | 'AI'
            | 'AX'
            | 'AL'
            | 'AD'
            | 'AE'
            | 'AR'
            | 'AM'
            | 'AS'
            | 'AQ'
            | 'TF'
            | 'AG'
            | 'AU'
            | 'AT'
            | 'AZ'
            | 'BI'
            | 'BE'
            | 'BJ'
            | 'BQ'
            | 'BF'
            | 'BD'
            | 'BG'
            | 'BH'
            | 'BS'
            | 'BA'
            | 'BL'
            | 'BY'
            | 'BZ'
            | 'BM'
            | 'BO'
            | 'BR'
            | 'BB'
            | 'BN'
            | 'BT'
            | 'BV'
            | 'BW'
            | 'CF'
            | 'CA'
            | 'CC'
            | 'CH'
            | 'CL'
            | 'CN'
            | 'CI'
            | 'CM'
            | 'CD'
            | 'CG'
            | 'CK'
            | 'CO'
            | 'KM'
            | 'CV'
            | 'CR'
            | 'CU'
            | 'CW'
            | 'CX'
            | 'KY'
            | 'CY'
            | 'CZ'
            | 'DE'
            | 'DJ'
            | 'DM'
            | 'DK'
            | 'DO'
            | 'DZ'
            | 'EC'
            | 'EG'
            | 'ER'
            | 'EH'
            | 'ES'
            | 'EE'
            | 'ET'
            | 'FI'
            | 'FJ'
            | 'FK'
            | 'FR'
            | 'FO'
            | 'FM'
            | 'GA'
            | 'GB'
            | 'GE'
            | 'GG'
            | 'GH'
            | 'GI'
            | 'GN'
            | 'GP'
            | 'GM'
            | 'GW'
            | 'GQ'
            | 'GR'
            | 'GD'
            | 'GL'
            | 'GT'
            | 'GF'
            | 'GU'
            | 'GY'
            | 'HK'
            | 'HM'
            | 'HN'
            | 'HR'
            | 'HT'
            | 'HU'
            | 'ID'
            | 'IM'
            | 'IN'
            | 'IO'
            | 'IE'
            | 'IR'
            | 'IQ'
            | 'IS'
            | 'IL'
            | 'IT'
            | 'JM'
            | 'JE'
            | 'JO'
            | 'JP'
            | 'KZ'
            | 'KE'
            | 'KG'
            | 'KH'
            | 'KI'
            | 'KN'
            | 'KR'
            | 'KW'
            | 'LA'
            | 'LB'
            | 'LR'
            | 'LY'
            | 'LC'
            | 'LI'
            | 'LK'
            | 'LS'
            | 'LT'
            | 'LU'
            | 'LV'
            | 'MO'
            | 'MF'
            | 'MA'
            | 'MC'
            | 'MD'
            | 'MG'
            | 'MV'
            | 'MX'
            | 'MH'
            | 'MK'
            | 'ML'
            | 'MT'
            | 'MM'
            | 'ME'
            | 'MN'
            | 'MP'
            | 'MZ'
            | 'MR'
            | 'MS'
            | 'MQ'
            | 'MU'
            | 'MW'
            | 'MY'
            | 'YT'
            | 'NA'
            | 'NC'
            | 'NE'
            | 'NF'
            | 'NG'
            | 'NI'
            | 'NU'
            | 'NL'
            | 'NO'
            | 'NP'
            | 'NR'
            | 'NZ'
            | 'OM'
            | 'PK'
            | 'PA'
            | 'PN'
            | 'PE'
            | 'PH'
            | 'PW'
            | 'PG'
            | 'PL'
            | 'PR'
            | 'KP'
            | 'PT'
            | 'PY'
            | 'PS'
            | 'PF'
            | 'QA'
            | 'RE'
            | 'RO'
            | 'RU'
            | 'RW'
            | 'SA'
            | 'SD'
            | 'SN'
            | 'SG'
            | 'GS'
            | 'SH'
            | 'SJ'
            | 'SB'
            | 'SL'
            | 'SV'
            | 'SM'
            | 'SO'
            | 'PM'
            | 'RS'
            | 'SS'
            | 'ST'
            | 'SR'
            | 'SK'
            | 'SI'
            | 'SE'
            | 'SZ'
            | 'SX'
            | 'SC'
            | 'SY'
            | 'TC'
            | 'TD'
            | 'TG'
            | 'TH'
            | 'TJ'
            | 'TK'
            | 'TM'
            | 'TL'
            | 'TO'
            | 'TT'
            | 'TN'
            | 'TR'
            | 'TV'
            | 'TW'
            | 'TZ'
            | 'UG'
            | 'UA'
            | 'UM'
            | 'UY'
            | 'US'
            | 'UZ'
            | 'VA'
            | 'VC'
            | 'VE'
            | 'VG'
            | 'VI'
            | 'VN'
            | 'VU'
            | 'WF'
            | 'WS'
            | 'YE'
            | 'ZA'
            | 'ZM'
            | 'ZW'
            | 'ZZ';
        /**
         * Date
         * Format: date
         * @example [
         *       "2024-06-31"
         *     ]
         */
        Date: string;
        /**
         * entity type
         * @enum {string}
         */
        EntityType: 'individual' | 'corporate';
        /** Individual entity */
        IndividualEntity: {
            id?: components['schemas']['EntityID'];
            /** @example Joshuah Grant */
            name?: string;
            /**
             * Format: email
             * @example Flavio_Cartwright37@gmail.com
             */
            email?: string;
            created_at?: components['schemas']['Datetime'];
            gender?: components['schemas']['Gender'];
            /** @example Joshuah */
            first_name?: string;
            /** @example Grant */
            last_name?: string;
            /** @example 9 Jurong Town Hall Rd #01-50 iHub S() */
            street?: string;
            /** @example singapore */
            city?: string;
            /** @example 609431 */
            postal_code?: string;
            country?: components['schemas']['CountryCode2'];
            nationality?: components['schemas']['CountryCode2'];
            birth_country?: components['schemas']['CountryCode2'];
            birth_date?: components['schemas']['Date'];
            /** @example paris */
            birth_place?: string;
            entity_type?: components['schemas']['EntityType'];
        };
        /** corporate entity */
        CorporateEntity: {
            id?: components['schemas']['EntityID'];
            /** @example Wisoky - Berge */
            name?: string;
            /**
             * Format: email
             * @example mercedes_oconner@yahoo.com
             */
            email?: string;
            created_at?: components['schemas']['Datetime'];
            /** @example 160 Lor 1 Toa Payoh #01-1564 */
            street?: string;
            /** @example singapore */
            city?: string;
            /** @example 310160 */
            postal_code?: string;
            country?: components['schemas']['CountryCode2'];
            /** @example Wisoky - Berge */
            company_name?: string;
            registration_country?: components['schemas']['CountryCode2'];
            incorporation_date?: components['schemas']['Date'];
            entity_type?: components['schemas']['EntityType'];
        };
        /**
         * Risk Assessment Status
         * @enum {string}
         */
        RiskAssessmentStatus: 'accepted' | 'created' | 'rejected' | 'expired';
        /**
         * Legal Entity Risk Level
         * @enum {string}
         */
        ComplianceRiskLevel: 'unknown' | 'low' | 'medium' | 'high';
        /**
         * onboarding mode
         * @enum {string}
         */
        OnboardingMode: 'face_to_face' | 'non_face_to_face';
        /**
         * KYB status
         * @enum {string}
         */
        KybStatus: 'accepted' | 'pending' | 'rejected';
        /** EntityAddress */
        EntityAddress: {
            id: string;
            /** @example 1st main street */
            address_line_one?: string;
            /** @example Tower One #01-50 */
            address_line_two?: string;
            /** @example SG */
            city?: string;
            /** @example Singapore */
            state_region?: string;
            /** @example 609431 */
            postal_code?: string;
            country: components['schemas']['CountryCode2'];
        };
        /** LegalEntityIndividual */
        LegalEntityIndividual: {
            /** @example legent-01hzy23cq44ae6k7vy5jtp8bef */
            id?: string;
            /** @enum {string} */
            entity_type?: 'individual';
            /** @example John */
            first_name?: string;
            /** @example Doe */
            last_name?: string;
            /** @example [
             *       "John D"
             *     ] */
            alias_names?: string[];
            gender?: components['schemas']['Gender'];
            nationalities?: components['schemas']['CountryCode2'][];
            birth_country?: components['schemas']['CountryCode2'];
            birth_date?: components['schemas']['Date'];
            residence_country?: components['schemas']['CountryCode2'];
            /** @example International Passport */
            identity_document_type?: string;
            /** @example 123456 */
            identity_document_number?: string;
            identity_document_issue_date?: components['schemas']['Date'];
            identity_document_expiry_date?: components['schemas']['Date'];
            /** @example [
             *       "Investors",
             *       "Revenue"
             *     ] */
            sources_of_fund?: string[];
            risk_assessment_status?: components['schemas']['RiskAssessmentStatus'];
            calculated_risk_level?: components['schemas']['ComplianceRiskLevel'];
            /** @example Software Developer */
            occupation?: string;
            concluded_risk_level?: components['schemas']['ComplianceRiskLevel'];
            /** @example john.doe@example.com */
            concluded_by?: string;
            concluded_at?: components['schemas']['Datetime'];
            onboarding_mode?: components['schemas']['OnboardingMode'];
            kyb_status?: components['schemas']['KybStatus'];
            approved_at?: components['schemas']['Datetime'];
            risk_level?: components['schemas']['ComplianceRiskLevel'];
            addresses?: components['schemas']['EntityAddress'][];
            created_at?: components['schemas']['Datetime'];
        };
        /** LegalEntityCorporate */
        LegalEntityCorporate: {
            /** @example legent-01hzy23cq44ae6k7vy5jtp8bef */
            id?: string;
            /** @enum {string} */
            entity_type?: 'corporate';
            /** @example Example Corp */
            company_name?: string;
            /** @example [
             *       "Example Corp"
             *     ] */
            alias_names?: string[];
            /** @example [
             *       "Example Corp"
             *     ] */
            trade_names?: string[];
            /** @example [
             *       "Example Corp"
             *     ] */
            former_registered_names?: string[];
            incorporation_date?: components['schemas']['Date'];
            /** @example 12345678 */
            incorporation_number?: string;
            incorporation_country?: components['schemas']['CountryCode2'];
            operation_countries?: components['schemas']['CountryCode2'][];
            /** @example [
             *       "https://example.com",
             *       "https://example.org"
             *     ] */
            websites?: string[];
            /** @example Technology */
            industry?: string;
            /** @example 1 */
            industry_id?: number;
            /** @example [
             *       "1234",
             *       "5678"
             *     ] */
            mcc_codes?: string[];
            /** @example [
             *       "Software Development",
             *       "Consulting"
             *     ] */
            business_activities?: string[];
            /** @example [
             *       "Investors",
             *       "Revenue"
             *     ] */
            sources_of_fund?: string[];
            onboarding_mode?: components['schemas']['OnboardingMode'];
            kyb_status?: components['schemas']['KybStatus'];
            approved_at?: components['schemas']['Datetime'];
            risk_level?: components['schemas']['ComplianceRiskLevel'];
            addresses?: components['schemas']['EntityAddress'][];
            risk_assessment_status?: components['schemas']['RiskAssessmentStatus'];
            calculated_risk_level?: components['schemas']['ComplianceRiskLevel'];
            concluded_risk_level?: components['schemas']['ComplianceRiskLevel'];
            /** @example john.doe@example.com */
            concluded_by?: string;
            concluded_at?: components['schemas']['Datetime'];
            created_at?: components['schemas']['Datetime'];
        };
        /**
         * LegalEntityID
         * @description legal entity id
         * @example legent-ykrit3642ha2gzdthfagghbnme
         */
        LegalEntityID: string;
        /**
         * LegalEntityRelatedPartyID
         * @description legal entity related party id
         * @example lentrp-ykrit3642ha2gzdthfagghbnme
         */
        LegalEntityRelatedPartyID: string;
        /**
         * RelatedPartyRoles
         * @example director
         * @enum {string}
         */
        RelatedPartyRoles:
            | 'director'
            | 'shareholder'
            | 'ultimate_beneficial_owner'
            | 'other'
            | 'unknown';
        /** LegalEntityRelatedPartyIndividual */
        LegalEntityRelatedPartyIndividual: {
            id?: components['schemas']['LegalEntityRelatedPartyID'];
            /** @enum {string} */
            entity_type?: 'individual';
            /** @example John */
            first_name?: string;
            /** @example Doe */
            last_name?: string;
            /** @example [
             *       "John"
             *     ] */
            alias_names?: string[];
            gender?: components['schemas']['Gender'];
            nationalities?: components['schemas']['CountryCode2'][];
            birth_country?: components['schemas']['CountryCode2'];
            birth_date?: components['schemas']['Date'];
            residence_country?: components['schemas']['CountryCode2'];
            /** @example International Passport */
            identity_document_type?: string;
            /** @example 123456 */
            identity_document_number?: string;
            identity_document_issue_date?: components['schemas']['Date'];
            identity_document_expiry_date?: components['schemas']['Date'];
            addresses?: components['schemas']['EntityAddress'][];
            roles?: components['schemas']['RelatedPartyRoles'][];
        };
        /** LegalEntityRelatedPartyCorporate */
        LegalEntityRelatedPartyCorporate: {
            id?: components['schemas']['LegalEntityRelatedPartyID'];
            /** @enum {string} */
            entity_type?: 'corporate';
            /** @example Example Corp */
            company_name?: string;
            /** @example [
             *       "Example Corp"
             *     ] */
            alias_names?: string[];
            /** @example [
             *       "Example Corp"
             *     ] */
            trade_names?: string[];
            /** @example [
             *       "Example Corp"
             *     ] */
            former_registered_names?: string[];
            incorporation_date?: components['schemas']['Date'];
            /** @example 12345678 */
            incorporation_number?: string;
            incorporation_country?: components['schemas']['CountryCode2'];
            operation_countries?: components['schemas']['CountryCode2'][];
            /** @example [
             *       "https://example.com",
             *       "https://example.org"
             *     ] */
            websites?: string[];
            /** @example Technology */
            industry?: string;
            /** @example [
             *       "1234",
             *       "5678"
             *     ] */
            mcc_codes?: string[];
            /** @example [
             *       "Software Development",
             *       "Consulting"
             *     ] */
            business_activities?: string[];
            addresses?: components['schemas']['EntityAddress'][];
            roles?: components['schemas']['RelatedPartyRoles'][];
            /** @example 1 */
            ownership_structure?: number;
        };
        /**
         * Transaction
         * @description transaction
         */
        Transaction: {
            id?: string;
            from_account_id?: components['schemas']['AccountID'];
            to_account_id?: components['schemas']['AccountID'];
            amount?: components['schemas']['Decimal'];
            created_at?: components['schemas']['Datetime'];
        };
    };
    responses: {
        /** @description RFC 9457: Problem Details for HTTP APIs
         *     https://www.rfc-editor.org/rfc/rfc9457.html */
        'problem-detail': {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json': components['schemas']['ProblemDetail'];
            };
        };
        /** @description Example response */
        'account-response': {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json':
                    | components['schemas']['BankAccount']
                    | components['schemas']['VirtualAccount']
                    | components['schemas']['CryptoAccount'];
            };
        };
        /** @description Example response */
        'get-balance-response': {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json': components['schemas']['Balance'];
            };
        };
        /** @description List of accounts */
        'account-list': {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json': {
                    /** @example true */
                    has_more: boolean;
                    data: (
                        | components['schemas']['BankAccount']
                        | components['schemas']['VirtualAccount']
                        | components['schemas']['CryptoAccount']
                    )[];
                };
            };
        };
        /** @description List of transactions */
        'transaction-list': {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json': {
                    /** @example true */
                    has_more: boolean;
                    data: components['schemas']['LedgerTransaction'][];
                };
            };
        };
        /** @description Example response */
        'entity-response': {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json':
                    | components['schemas']['IndividualEntity']
                    | components['schemas']['CorporateEntity'];
            };
        };
        /** @description List of entities */
        'entity-list': {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json': {
                    /** @example true */
                    has_more: boolean;
                    data: (
                        | components['schemas']['IndividualEntity']
                        | components['schemas']['CorporateEntity']
                    )[];
                };
            };
        };
        /** @description Example response */
        'legal-entity': {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json':
                    | components['schemas']['LegalEntityIndividual']
                    | components['schemas']['LegalEntityCorporate'];
            };
        };
        /** @description List of legal entities */
        'legal-entity-list': {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json': {
                    /** @example true */
                    has_more: boolean;
                    data: (
                        | components['schemas']['LegalEntityIndividual']
                        | components['schemas']['LegalEntityCorporate']
                    )[];
                };
            };
        };
        /** @description Example response */
        'legal-entity-related-party': {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json':
                    | components['schemas']['LegalEntityRelatedPartyIndividual']
                    | components['schemas']['LegalEntityRelatedPartyCorporate'];
            };
        };
        /** @description List of related parties */
        'legal-entity-related-party-list': {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json': {
                    /** @example true */
                    has_more: boolean;
                    data: (
                        | components['schemas']['LegalEntityRelatedPartyIndividual']
                        | components['schemas']['LegalEntityRelatedPartyCorporate']
                    )[];
                };
            };
        };
        /** @description Example response */
        'transaction-response': {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json': components['schemas']['Transaction'];
            };
        };
        /** @description Example response */
        'list-industry-response': {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json': {
                    data: {
                        /** @example 1 */
                        id?: string;
                        /** @example Technology */
                        label?: string;
                    }[];
                };
            };
        };
        /** @description Example response */
        'list-occupation-response': {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json': {
                    data: {
                        /** @example 1 */
                        id?: string;
                        /** @example Technology */
                        label?: string;
                    }[];
                };
            };
        };
    };
    parameters: {
        /** @description number of records to be returned */
        limit: number;
        /** @description last id of the current list to fetch the next page */
        starting_after: string;
        /** @description first id of the current list to fetch the previous page */
        ending_before: string;
        'X-Idempotency-Key': components['schemas']['UUIDv7'];
    };
    requestBodies: {
        'create-entity': {
            content: {
                'application/json': components['schemas']['CreateEntity'];
            };
        };
        'create-account': {
            content: {
                'application/json': {
                    entity_id: components['schemas']['EntityID'];
                    account_category: components['schemas']['AccountCategory'];
                    account_locality: components['schemas']['AccountLocality'];
                    label: components['schemas']['Label'];
                    network_currency_id: components['schemas']['AnyNetworkCurrencyID'];
                    /**
                     * @description 0nly if the account locality is external and account category is bank account
                     * @example FR7616408000020100000037430
                     */
                    IBAN?: string;
                    /**
                     * @description 0nly if the account locality is external and account category is bank account
                     * @example CRLYFRPPXXX
                     */
                    BIC?: string;
                };
            };
        };
        'create-legal-entity': {
            content: {
                'application/json': components['schemas']['CreateLegalEntity'];
            };
        };
        'update-legal-entity': {
            content: {
                'application/json': components['schemas']['UpdateLegalEntity'];
            };
        };
        'create-legal-entity-related-party': {
            content: {
                'application/json': components['schemas']['CreateLegalEntityRelatedParty'];
            };
        };
        'update-legal-entity-related-party': {
            content: {
                'application/json': components['schemas']['UpdateLegalEntityRelatedParty'];
            };
        };
        'create-transaction': {
            content: {
                'application/json': components['schemas']['CreateTransaction'];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    'get-admin-api-v1-latest-rates': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Rates'];
                };
            };
            '5XX': components['responses']['problem-detail'];
        };
    };
    'get-admin-api-v1-accounts-account-id': {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description account id */
                'account-id': components['schemas']['AccountID'];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components['responses']['account-response'];
            400: components['responses']['problem-detail'];
            404: components['responses']['problem-detail'];
            '5XX': components['responses']['problem-detail'];
        };
    };
    'get-admin-api-v1-accounts-account-id-balance': {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description account id */
                'account-id': components['schemas']['AccountID'];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components['responses']['get-balance-response'];
            400: components['responses']['problem-detail'];
            404: components['responses']['problem-detail'];
            '5XX': components['responses']['problem-detail'];
        };
    };
    'get-admin-api-v1-accounts-account-id-transactions': {
        parameters: {
            query?: {
                /** @description number of records to be returned */
                limit?: components['parameters']['limit'];
                /** @description last id of the current list to fetch the next page */
                starting_after?: components['parameters']['starting_after'];
                /** @description first id of the current list to fetch the previous page */
                ending_before?: components['parameters']['ending_before'];
            };
            header?: never;
            path: {
                /** @description account id */
                'account-id': components['schemas']['AccountID'];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components['responses']['transaction-list'];
            400: components['responses']['problem-detail'];
            404: components['responses']['problem-detail'];
            '5XX': components['responses']['problem-detail'];
        };
    };
    'get-admin-api-v1-accounts': {
        parameters: {
            query?: {
                account_locality?: components['schemas']['AccountLocality'];
                /** @description number of records to be returned */
                limit?: components['parameters']['limit'];
                /** @description last id of the current list to fetch the next page */
                starting_after?: components['parameters']['starting_after'];
                /** @description first id of the current list to fetch the previous page */
                ending_before?: components['parameters']['ending_before'];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components['responses']['account-list'];
            400: components['responses']['problem-detail'];
            404: components['responses']['problem-detail'];
            '5XX': components['responses']['problem-detail'];
        };
    };
    'post-admin-api-v1-accounts': {
        parameters: {
            query?: never;
            header: {
                'X-Idempotency-Key': components['parameters']['X-Idempotency-Key'];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: components['requestBodies']['create-account'];
        responses: {
            201: components['responses']['account-response'];
            /** @description accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components['responses']['problem-detail'];
            409: components['responses']['problem-detail'];
            '5XX': components['responses']['problem-detail'];
        };
    };
    'get-admin-api-v1-entities': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components['responses']['entity-list'];
            400: components['responses']['problem-detail'];
            404: components['responses']['problem-detail'];
            '5XX': components['responses']['problem-detail'];
        };
    };
    'post-admin-api-v1-entities': {
        parameters: {
            query?: never;
            header: {
                'X-Idempotency-Key': components['parameters']['X-Idempotency-Key'];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: components['requestBodies']['create-entity'];
        responses: {
            201: components['responses']['entity-response'];
            400: components['responses']['problem-detail'];
            409: components['responses']['problem-detail'];
            '5XX': components['responses']['problem-detail'];
        };
    };
    'get-admin-api-v1-entity': {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description entity id */
                'entity-id': components['schemas']['EntityID'];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components['responses']['entity-response'];
            400: components['responses']['problem-detail'];
            404: components['responses']['problem-detail'];
            '5XX': components['responses']['problem-detail'];
        };
    };
    'get-admin-api-v1-entity-accounts': {
        parameters: {
            query?: {
                /** @description number of records to be returned */
                limit?: components['parameters']['limit'];
                /** @description last id of the current list to fetch the next page */
                starting_after?: components['parameters']['starting_after'];
                /** @description first id of the current list to fetch the previous page */
                ending_before?: components['parameters']['ending_before'];
            };
            header?: never;
            path: {
                /** @description entity id */
                'entity-id': components['schemas']['EntityID'];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components['responses']['account-list'];
            400: components['responses']['problem-detail'];
            404: components['responses']['problem-detail'];
            '5XX': components['responses']['problem-detail'];
        };
    };
    'get-admin-api-v1-legal-entities': {
        parameters: {
            query?: {
                /** @description number of records to be returned */
                limit?: components['parameters']['limit'];
                /** @description last id of the current list to fetch the next page */
                starting_after?: components['parameters']['starting_after'];
                /** @description first id of the current list to fetch the previous page */
                ending_before?: components['parameters']['ending_before'];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components['responses']['legal-entity-list'];
            400: components['responses']['problem-detail'];
            404: components['responses']['problem-detail'];
            '5XX': components['responses']['problem-detail'];
        };
    };
    'post-admin-api-v1-compliance-legal-entities': {
        parameters: {
            query?: never;
            header: {
                'X-Idempotency-Key': components['parameters']['X-Idempotency-Key'];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: components['requestBodies']['create-legal-entity'];
        responses: {
            201: components['responses']['legal-entity'];
            400: components['responses']['problem-detail'];
            409: components['responses']['problem-detail'];
            '5XX': components['responses']['problem-detail'];
        };
    };
    'get-admin-api-v1-compliance-legal-entities': {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description legal entity id */
                'legal-entity-id': components['schemas']['LegalEntityID'];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components['responses']['legal-entity'];
            400: components['responses']['problem-detail'];
            404: components['responses']['problem-detail'];
            '5XX': components['responses']['problem-detail'];
        };
    };
    'update-admin-api-v1-compliance-legal-entities': {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description legal entity id */
                'legal-entity-id': components['schemas']['LegalEntityID'];
            };
            cookie?: never;
        };
        requestBody?: components['requestBodies']['update-legal-entity'];
        responses: {
            200: components['responses']['legal-entity'];
            400: components['responses']['problem-detail'];
            404: components['responses']['problem-detail'];
            409: components['responses']['problem-detail'];
            '5XX': components['responses']['problem-detail'];
        };
    };
    'delete-admin-api-v1-compliance-legal-entities': {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description legal entity id */
                'legal-entity-id': components['schemas']['LegalEntityID'];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components['responses']['problem-detail'];
            '5XX': components['responses']['problem-detail'];
        };
    };
    'get-admin-api-v1-compliance-legal-entities-related-parties': {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description legal entity id */
                'legal-entity-id': components['schemas']['LegalEntityID'];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components['responses']['legal-entity-related-party-list'];
            400: components['responses']['problem-detail'];
            404: components['responses']['problem-detail'];
            '5XX': components['responses']['problem-detail'];
        };
    };
    'post-admin-api-v1-compliance-legal-entities-related-party': {
        parameters: {
            query?: never;
            header: {
                'X-Idempotency-Key': components['parameters']['X-Idempotency-Key'];
            };
            path: {
                /** @description legal entity id */
                'legal-entity-id': components['schemas']['LegalEntityID'];
            };
            cookie?: never;
        };
        requestBody?: components['requestBodies']['create-legal-entity-related-party'];
        responses: {
            201: components['responses']['legal-entity-related-party'];
            400: components['responses']['problem-detail'];
            409: components['responses']['problem-detail'];
            '5XX': components['responses']['problem-detail'];
        };
    };
    'get-admin-api-v1-compliance-legal-entities-related-party': {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description legal entity id */
                'legal-entity-id': components['schemas']['LegalEntityID'];
                /** @description related party id */
                'related-party-id': components['schemas']['LegalEntityRelatedPartyID'];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components['responses']['legal-entity-related-party'];
            400: components['responses']['problem-detail'];
            404: components['responses']['problem-detail'];
            '5XX': components['responses']['problem-detail'];
        };
    };
    'update-admin-api-v1-compliance-legal-entities-related-party': {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description legal entity id */
                'legal-entity-id': components['schemas']['LegalEntityID'];
                /** @description related party id */
                'related-party-id': components['schemas']['LegalEntityRelatedPartyID'];
            };
            cookie?: never;
        };
        requestBody?: components['requestBodies']['update-legal-entity-related-party'];
        responses: {
            200: components['responses']['legal-entity-related-party'];
            400: components['responses']['problem-detail'];
            404: components['responses']['problem-detail'];
            409: components['responses']['problem-detail'];
            '5XX': components['responses']['problem-detail'];
        };
    };
    'delete-admin-api-v1-compliance-legal-entities-related-party': {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description legal entity id */
                'legal-entity-id': components['schemas']['LegalEntityID'];
                /** @description related party id */
                'related-party-id': components['schemas']['LegalEntityRelatedPartyID'];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components['responses']['problem-detail'];
            '5XX': components['responses']['problem-detail'];
        };
    };
    'post-admin-api-v1-transaction': {
        parameters: {
            query?: never;
            header: {
                'X-Idempotency-Key': components['parameters']['X-Idempotency-Key'];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: components['requestBodies']['create-transaction'];
        responses: {
            201: components['responses']['transaction-response'];
            /** @description accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components['responses']['problem-detail'];
            409: components['responses']['problem-detail'];
            '5XX': components['responses']['problem-detail'];
        };
    };
    'get-admin-api-v1-const-industries': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components['responses']['list-industry-response'];
            400: components['responses']['problem-detail'];
            404: components['responses']['problem-detail'];
            '5XX': components['responses']['problem-detail'];
        };
    };
    'get-admin-api-v1-const-occupations': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components['responses']['list-occupation-response'];
            400: components['responses']['problem-detail'];
            404: components['responses']['problem-detail'];
            '5XX': components['responses']['problem-detail'];
        };
    };
}
