type IsDictionary<T> = Record<string, object> &
    Record<string, number> &
    Record<string, string> extends T
    ? true
    : false;

/**
 * Strip undefined from Record types. tsconfig's noUncheckedIndexedAccess
 * already warns possible undefined property value.
 **/
export type APIResponse<T> =
    IsDictionary<T> extends true
        ? { [K in keyof T]: APIResponse<NonNullable<T[K]>> }
        : T extends object
          ? { [K in keyof T]: APIResponse<T[K]> }
          : T;

export interface CFCredendial {
    AccessClientID: string;
    AccessClientSecret: string;
}

export enum AccountCategory {
    'Bank account' = 'bank_account',
    'Crypto account' = 'crypto_account',
    'Virtual account' = 'virtual_account',
}

export enum CreateAccountNetworkCurrencyId {
    EUR = 'EUR',
}

export enum AccountLocality {
    Internal = 'internal',
    External = 'external',
}

export enum Gender {
    Male = 'male',
    Female = 'female',
    Other = 'other',
}

export enum CountryCode2 {
    Aruba = 'AW',
    Afghanistan = 'AF',
    Angola = 'AO',
    Anguilla = 'AI',
    AlandIslands = 'AX',
    Albania = 'AL',
    Andorra = 'AD',
    UnitedArabEmirates = 'AE',
    Argentina = 'AR',
    Armenia = 'AM',
    AmericanSamoa = 'AS',
    Antarctica = 'AQ',
    FrenchSouthernTerritories = 'TF',
    AntiguaAndBarbuda = 'AG',
    Australia = 'AU',
    Austria = 'AT',
    Azerbaijan = 'AZ',
    Burundi = 'BI',
    Belgium = 'BE',
    Benin = 'BJ',
    BonaireSintEustatiusAndSaba = 'BQ',
    BurkinaFaso = 'BF',
    Bangladesh = 'BD',
    Bulgaria = 'BG',
    Bahrain = 'BH',
    Bahamas = 'BS',
    BosniaAndHerzegovina = 'BA',
    SaintBarthelemy = 'BL',
    Belarus = 'BY',
    Belize = 'BZ',
    Bermuda = 'BM',
    Bolivia = 'BO',
    Brazil = 'BR',
    Barbados = 'BB',
    BruneiDarussalam = 'BN',
    Bhutan = 'BT',
    BouvetIsland = 'BV',
    Botswana = 'BW',
    CentralAfricanRepublic = 'CF',
    Canada = 'CA',
    CocosIslands = 'CC',
    Switzerland = 'CH',
    Chile = 'CL',
    China = 'CN',
    IvoryCoast = 'CI',
    Cameroon = 'CM',
    CongoKinshasa = 'CD',
    CongoBrazzaville = 'CG',
    CookIslands = 'CK',
    Colombia = 'CO',
    Comoros = 'KM',
    CapeVerde = 'CV',
    CostaRica = 'CR',
    Cuba = 'CU',
    Curacao = 'CW',
    ChristmasIsland = 'CX',
    CaymanIslands = 'KY',
    Cyprus = 'CY',
    CzechRepublic = 'CZ',
    Germany = 'DE',
    Djibouti = 'DJ',
    Dominica = 'DM',
    Denmark = 'DK',
    DominicanRepublic = 'DO',
    Algeria = 'DZ',
    Ecuador = 'EC',
    Egypt = 'EG',
    Eritrea = 'ER',
    WesternSahara = 'EH',
    Spain = 'ES',
    Estonia = 'EE',
    Ethiopia = 'ET',
    Finland = 'FI',
    Fiji = 'FJ',
    FalklandIslands = 'FK',
    France = 'FR',
    FaroeIslands = 'FO',
    Micronesia = 'FM',
    Gabon = 'GA',
    UnitedKingdom = 'GB',
    Georgia = 'GE',
    Guernsey = 'GG',
    Ghana = 'GH',
    Gibraltar = 'GI',
    Guinea = 'GN',
    Guadeloupe = 'GP',
    Gambia = 'GM',
    GuineaBissau = 'GW',
    EquatorialGuinea = 'GQ',
    Greece = 'GR',
    Grenada = 'GD',
    Greenland = 'GL',
    Guatemala = 'GT',
    FrenchGuiana = 'GF',
    Guam = 'GU',
    Guyana = 'GY',
    HongKong = 'HK',
    HeardIslandAndMcdonaldIslands = 'HM',
    Honduras = 'HN',
    Croatia = 'HR',
    Haiti = 'HT',
    Hungary = 'HU',
    Indonesia = 'ID',
    IsleOfMan = 'IM',
    India = 'IN',
    BritishIndianOceanTerritory = 'IO',
    Ireland = 'IE',
    Iran = 'IR',
    Iraq = 'IQ',
    Iceland = 'IS',
    Israel = 'IL',
    Italy = 'IT',
    Jamaica = 'JM',
    Jersey = 'JE',
    Jordan = 'JO',
    Japan = 'JP',
    Kazakhstan = 'KZ',
    Kenya = 'KE',
    Kyrgyzstan = 'KG',
    Cambodia = 'KH',
    Kiribati = 'KI',
    SaintKittsAndNevis = 'KN',
    SouthKorea = 'KR',
    Kuwait = 'KW',
    Laos = 'LA',
    Lebanon = 'LB',
    Liberia = 'LR',
    Libya = 'LY',
    SaintLucia = 'LC',
    Liechtenstein = 'LI',
    SriLanka = 'LK',
    Lesotho = 'LS',
    Lithuania = 'LT',
    Luxembourg = 'LU',
    Latvia = 'LV',
    Macau = 'MO',
    SaintMartin = 'MF',
    Morocco = 'MA',
    Monaco = 'MC',
    Moldova = 'MD',
    Madagascar = 'MG',
    Maldives = 'MV',
    Mexico = 'MX',
    MarshallIslands = 'MH',
    NorthMacedonia = 'MK',
    Mali = 'ML',
    Malta = 'MT',
    Myanmar = 'MM',
    Montenegro = 'ME',
    Mongolia = 'MN',
    NorthernMarianaIslands = 'MP',
    Mozambique = 'MZ',
    Mauritania = 'MR',
    Montserrat = 'MS',
    Martinique = 'MQ',
    Mauritius = 'MU',
    Malawi = 'MW',
    Malaysia = 'MY',
    Mayotte = 'YT',
    Namibia = 'NA',
    NewCaledonia = 'NC',
    Niger = 'NE',
    NorfolkIsland = 'NF',
    Nigeria = 'NG',
    Nicaragua = 'NI',
    Niue = 'NU',
    Netherlands = 'NL',
    Norway = 'NO',
    Nepal = 'NP',
    Nauru = 'NR',
    NewZealand = 'NZ',
    Oman = 'OM',
    Pakistan = 'PK',
    Panama = 'PA',
    Pitcairn = 'PN',
    Peru = 'PE',
    Philippines = 'PH',
    Palau = 'PW',
    PapuaNewGuinea = 'PG',
    Poland = 'PL',
    PuertoRico = 'PR',
    NorthKorea = 'KP',
    Portugal = 'PT',
    Paraguay = 'PY',
    Palestine = 'PS',
    FrenchPolynesia = 'PF',
    Qatar = 'QA',
    Reunion = 'RE',
    Romania = 'RO',
    Russia = 'RU',
    Rwanda = 'RW',
    SaudiArabia = 'SA',
    Sudan = 'SD',
    Senegal = 'SN',
    Singapore = 'SG',
    SouthGeorgiaAndTheSouthSandwichIslands = 'GS',
    SaintHelena = 'SH',
    SvalbardAndJanMayen = 'SJ',
    SolomonIslands = 'SB',
    SierraLeone = 'SL',
    ElSalvador = 'SV',
    SanMarino = 'SM',
    Somalia = 'SO',
    SaintPierreAndMiquelon = 'PM',
    Serbia = 'RS',
    SouthSudan = 'SS',
    SaoTomeAndPrincipe = 'ST',
    Suriname = 'SR',
    Slovakia = 'SK',
    Slovenia = 'SI',
    Sweden = 'SE',
    Eswatini = 'SZ',
    SintMaarten = 'SX',
    Seychelles = 'SC',
    Syria = 'SY',
    TurksAndCaicosIslands = 'TC',
    Chad = 'TD',
    Togo = 'TG',
    Thailand = 'TH',
    Tajikistan = 'TJ',
    Tokelau = 'TK',
    Turkmenistan = 'TM',
    TimorLeste = 'TL',
    Tonga = 'TO',
    TrinidadAndTobago = 'TT',
    Tunisia = 'TN',
    Turkey = 'TR',
    Tuvalu = 'TV',
    Taiwan = 'TW',
    Tanzania = 'TZ',
    Uganda = 'UG',
    Ukraine = 'UA',
    UnitedStatesMinorOutlyingIslands = 'UM',
    Uruguay = 'UY',
    UnitedStates = 'US',
    Uzbekistan = 'UZ',
    VaticanCity = 'VA',
    SaintVincentAndTheGrenadines = 'VC',
    Venezuela = 'VE',
    BritishVirginIslands = 'VG',
    UnitedStatesVirginIslands = 'VI',
    Vietnam = 'VN',
    Vanuatu = 'VU',
    WallisAndFutuna = 'WF',
    Samoa = 'WS',
    Yemen = 'YE',
    SouthAfrica = 'ZA',
    Zambia = 'ZM',
    Zimbabwe = 'ZW',
}
