#!/bin/bash

while read local_ref local_sha remote_ref remote_sha; do
    echo "local_ref: $local_ref"
    echo "local_sha: $local_sha"
    echo "remote_ref: $remote_ref"
    echo "remote_sha: $remote_sha"

    current_branch=$(git branch --show-current)
    
    

    if [[ "$remote_ref" =~ refs/tags/ ]]; then
        TAG_NAME=${remote_ref#refs/tags/}

        if [[ "$current_branch" != "main" ]]; then
            echo "Error: You can only push to main branch"
            exit 1
        fi

        if [[ ! "$TAG_NAME" =~ ^v[0-9]{4}\.[0-9]{2}\.[0-9]{2}\.[0-9]{4}(-(staging|sandbox))?$ ]]; then
            echo "Error: Tag name format is incorrect.\nTags must follow the pattern vYYYY.MM.DD.HHmm, vYYYY.MM.DD.HHmm-staging, or vYYYY.MM.DD.HHmm-sandbox\nUse 'npm run tag:create:production', 'npm run tag:create:staging', or 'npm run tag:create:sandbox' for convenient" 
            exit 1
        fi
    fi
done
