name: aubesee-admin ci

on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - main
            - staging

jobs:
    build-and-test:
        environment:
          name: ${{ github.ref_name }}
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '21.5.0'
            
            # - name: Cloudflare Wrangler
            #   uses: cloudflare/wrangler-action@v3
            #   with:
            #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            #     accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            #     wranglerVersion: "3.57.2"
            #     command: |
            #       whoami
            #       pages deployment list --project-name aube-admin-fe

            # - name: Configure AWS Credentials
            #   uses: aws-actions/configure-aws-credentials@v1
            #   with:
            #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            #     aws-region: ${{ secrets.AWS_REGION }}

            # - name: Retrieve Secret from AWS Secrets Manager
            #   run: |
            #     SECRETS_JSON=$(aws secretsmanager get-secret-value --secret-id ${{ secrets.SECRET_NAME }} --query SecretString --output text)
            #     echo "USER_EMAIL=$(echo "$SECRETS_JSON" | jq -r '.USER_EMAIL')" > .env
            #     echo "USER_PW=$(echo "$SECRETS_JSON" | jq -r '.USER_PW')" >> .env

            - name: Install Dependencies & Build
              run: |
                echo "Install npm..."
                npm i -g npm@10.2.4
                echo "Install dependencies..."
                npm ci

                echo "PUBLIC_ADMINAPI_HOST: ${{ vars.PUBLIC_ADMINAPI_HOST }}" > .env
                echo "CF_ACCESS_CLIENT_ID: ${{ secrets.CF_ACCESS_CLIENT_ID }}" >> .env
                echo "CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}" >> .env
                
                echo "Build project..."
                npm run build
                echo "Build finshed..."

            - name: Upload svelte-kit Artifacts    
              uses: actions/upload-artifact@v4
              with:
                name: sveltekit-artifacts
                path: .svelte-kit

            - name: Run Unit Tests
              run: npm run test:unit

            # - name: Run e2e tests
            #   run: npm run test:e2e
    deployment:
        needs: build-and-test
        environment:
          name: ${{ github.ref_name }}
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main'
        steps:
            # - name: Checkout code
            #   uses: actions/checkout@v2

            - name: Download svelte-kit Artifacts
              uses: actions/download-artifact@v4
              with:
                name: sveltekit-artifacts
                path: .svelte-kit

            - name: Create Date Version Tag
              id: create_tag
              if: github.ref == 'refs/heads/main'
              run: |
                echo "Create date versioning tag..."
                TAG="v$(date +'%Y%m%d%H%M%S')"
                git tag $TAG

            - name: Deploy to Cloudflare Pages
              uses: cloudflare/wrangler-action@v3
              with:
                apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                wranglerVersion: "3.57.2"
                command: |
                  pages deploy ./.svelte-kit/cloudflare --project-name ${{ vars.CF_PROJECT_NAME }}

